# Crypto Trading Bot Configuration
# Local setup with XAMPP MySQL

# Trading Configuration
trading:
  mode: paper  # paper or live
  exchange: binance
  base_currency: USDT
  paper_balance: 10000.0
  symbols:
    - BTC/USDT
    - ETH/USDT
    - ADA/USDT
  timeframes:
    - 1m
    - 5m
    - 1h
    - 1d

# Exchange Configurations
exchanges:
  binance:
    api_key: ${BINANCE_API_KEY}
    secret_key: ${BINANCE_SECRET_KEY}
    sandbox: true
    timeout: 30
    rate_limit: true
  
  coinbase:
    api_key: ${COINBASE_API_KEY}
    secret_key: ${COINBASE_SECRET_KEY}
    passphrase: ${COINBASE_PASSPHRASE}
    sandbox: true
    timeout: 30

# Database Configuration (MySQL via XAMPP)
database:
  type: mysql
  host: localhost
  port: 3306
  name: crypto_trading_bot
  username: root
  password: ""  # Default XAMPP MySQL password is empty
  pool_size: 10
  max_overflow: 20
  echo: false

# Risk Management
risk:
  risk_per_trade: 2.0  # Percentage of portfolio per trade
  max_position_size: 10.0  # Maximum percentage of portfolio per position
  max_daily_loss: 5.0  # Maximum daily loss percentage
  stop_loss_percentage: 2.0  # Default stop loss percentage
  take_profit_percentage: 4.0  # Default take profit percentage
  max_open_positions: 5  # Maximum number of open positions
  correlation_threshold: 0.8  # Maximum correlation between positions

# Strategy Configuration
strategies:
  ma_crossover:
    enabled: true
    symbol: BTC/USDT
    timeframe: 1h
    fast_ma: 20
    slow_ma: 50
    volume_filter: true
    trend_filter: true
  
  rsi_strategy:
    enabled: true
    symbol: ETH/USDT
    timeframe: 1h
    rsi_period: 14
    overbought: 70
    oversold: 30
    divergence_enabled: true

# Data Configuration
data:
  sources:
    - exchange
    - websocket
  cache_enabled: true
  cache_duration: 300  # seconds
  websocket_enabled: true
  backup_enabled: true

# Notification Configuration
notifications:
  enabled: true
  default_channels:
    - email
  rate_limit: 60  # seconds between same notifications
  
  email:
    enabled: true
    smtp_server: smtp.gmail.com
    smtp_port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    from_email: ${EMAIL_FROM}
    to_emails:
      - ${EMAIL_TO}
    use_tls: true
    subject_prefix: "[Trading Bot]"
  
  telegram:
    enabled: false
    bot_token: ${TELEGRAM_BOT_TOKEN}
    chat_ids:
      - ${TELEGRAM_CHAT_ID}
    parse_mode: HTML
  
  webhook:
    enabled: false
    webhooks:
      - url: ${WEBHOOK_URL}
        headers:
          Authorization: "Bearer ${WEBHOOK_TOKEN}"
    format_type: json

# Logging Configuration
logging:
  level: INFO
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file_enabled: true
  file_path: logs/trading_bot.log
  file_max_size: 10485760  # 10MB
  file_backup_count: 5
  console_enabled: true

# Dashboard Configuration
dashboard:
  enabled: true
  host: 127.0.0.1
  port: 8000
  debug: true
  auto_reload: true

# Backtesting Configuration
backtesting:
  enabled: true
  start_date: "2023-01-01"
  end_date: "2023-12-31"
  initial_balance: 10000.0
  commission: 0.001  # 0.1%
  slippage: 0.0005  # 0.05%

# Security Configuration
security:
  encrypt_api_keys: true
  session_timeout: 3600  # seconds
  max_login_attempts: 5
  lockout_duration: 900  # seconds

# Performance Configuration
performance:
  max_workers: 4
  batch_size: 100
  update_interval: 5  # seconds
  cleanup_interval: 3600  # seconds
